// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TPartsOutsourcingOrder is the golang structure of table t_parts_outsourcing_order for DAO operations like Where/Data.
type TPartsOutsourcingOrder struct {
	g.Meta                 `orm:"table:t_parts_outsourcing_order, do:true"`
	Id                     interface{} // id
	PartsOutsourcingId     interface{} // 工序委外订单号
	Supplier               interface{} // 供应商
	OutputMaterialCode     interface{} // 产出物料编码
	OutputMaterialName     interface{} // 产出物料名称
	OutputRequiredQuantity interface{} // 产出需求数量
	OutputUnit             interface{} // 产出单位
	PlanedReceiveTime      *gtime.Time // 计划收货日期
	QuantityInWarehouse    interface{} // 已入库数量
	QuantityNotInWarehouse interface{} // 未入库数量
	InputMaterialCode      interface{} // 投入物料编码
	InputMaterialName      interface{} // 投入物料名称
	InputRequiredQuantity  interface{} // 投入需求数量
	InputRequiredUnit      interface{} // 投入需求单位
	DeliveryQuantity       interface{} // 已发货数量
	UndeliveryQuantity     interface{} // 未发货数量
	PlanedDeliveryTime     *gtime.Time // 计划发货日期
	OutApply               interface{} // 出库申请： 0 已发送 1 未发送
	CreatedAt              *gtime.Time // 创建时间
	UpdatedAt              *gtime.Time // 更新时间
	DeletedAt              *gtime.Time // 删除时间
}
