// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TProcurementOrder is the golang structure of table t_procurement_order for DAO operations like Where/Data.
type TProcurementOrder struct {
	g.Meta                 `orm:"table:t_procurement_order, do:true"`
	Id                     interface{} // id
	ProcurementId          interface{} // 采购订单号
	OrderDetailLineNum     interface{} // 订单详情行号
	Supplier               interface{} // 供应商
	MaterialId             interface{} // 物料编码
	MaterialName           interface{} // 物料名称
	QuantityRequired       interface{} // 需求数量
	QuantityInWarehouse    interface{} // 已入库数量
	QuantityNotInWarehouse interface{} // 未入库数量
	PurchasingUnit         interface{} // 采购单位
	SettlementUnit         interface{} // 结算单位
	PlanArrivalDate        *gtime.Time // 计划到货日期
	Status                 interface{} // 入库操作 0 未入库 1入库
	CreatedAt              *gtime.Time // 创建时间
	UpdatedAt              *gtime.Time // 更新时间
	DeletedAt              *gtime.Time // 删除时间
}
