// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TProductionOrder is the golang structure of table t_production_order for DAO operations like Where/Data.
type TProductionOrder struct {
	g.Meta                 `orm:"table:t_production_order, do:true"`
	Id                     interface{} // id
	ProductionId           interface{} // 生产订单号
	OutputMaterialCode     interface{} // 产出物料编码
	OutputMaterialName     interface{} // 产出物料名称
	OutputRequiredQuantity interface{} // 产出需求数量
	OutputUnit             interface{} // 产出单位
	QuantityInWarehouse    interface{} // 已入库数量
	QuantityNotInWarehouse interface{} // 未入库数量
	StartWorkTime          *gtime.Time // 开工时间
	PlanedCompletionTime   *gtime.Time // 计划完工时间
	InputMaterialCode      interface{} // 投入物料编码
	InputRequiredUnit      interface{} // 投入需求单位
	InputRequiredQuantity  interface{} // 投入需求数量
	ReceivedQuantity       interface{} // 已领数量
	UnreceivedQuantity     interface{} // 未领数量
	InApply                interface{} // 出库申请 0 未发送 1 已发送
	OutApply               interface{} // 入库申请 0 未发送 1 已发送
	CreatedAt              *gtime.Time // 创建时间
	UpdatedAt              *gtime.Time // 更新时间
	DeletedAt              *gtime.Time // 删除时间
}
