// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"xlsx2mysql/internal/dao/internal"
)

// internalTPartsOutsourcingOrderDao is internal type for wrapping internal DAO implements.
type internalTPartsOutsourcingOrderDao = *internal.TPartsOutsourcingOrderDao

// tPartsOutsourcingOrderDao is the data access object for table t_parts_outsourcing_order.
// You can define custom methods on it to extend its functionality as you wish.
type tPartsOutsourcingOrderDao struct {
	internalTPartsOutsourcingOrderDao
}

var (
	// TPartsOutsourcingOrder is globally public accessible object for table t_parts_outsourcing_order operations.
	TPartsOutsourcingOrder = tPartsOutsourcingOrderDao{
		internal.NewTPartsOutsourcingOrderDao(),
	}
)

// Fill with you ideas below.
