// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"xlsx2mysql/internal/dao/internal"
)

// internalTProcessOutsourcingOrderDao is internal type for wrapping internal DAO implements.
type internalTProcessOutsourcingOrderDao = *internal.TProcessOutsourcingOrderDao

// tProcessOutsourcingOrderDao is the data access object for table t_process_outsourcing_order.
// You can define custom methods on it to extend its functionality as you wish.
type tProcessOutsourcingOrderDao struct {
	internalTProcessOutsourcingOrderDao
}

var (
	// TProcessOutsourcingOrder is globally public accessible object for table t_process_outsourcing_order operations.
	TProcessOutsourcingOrder = tProcessOutsourcingOrderDao{
		internal.NewTProcessOutsourcingOrderDao(),
	}
)

// Fill with you ideas below.
