// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"xlsx2mysql/internal/dao/internal"
)

// internalTProcurementOrderDao is internal type for wrapping internal DAO implements.
type internalTProcurementOrderDao = *internal.TProcurementOrderDao

// tProcurementOrderDao is the data access object for table t_procurement_order.
// You can define custom methods on it to extend its functionality as you wish.
type tProcurementOrderDao struct {
	internalTProcurementOrderDao
}

var (
	// TProcurementOrder is globally public accessible object for table t_procurement_order operations.
	TProcurementOrder = tProcurementOrderDao{
		internal.NewTProcurementOrderDao(),
	}
)

// Fill with you ideas below.
