// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TPartsOutsourcingOrder is the golang structure for table t_parts_outsourcing_order.
type TPartsOutsourcingOrder struct {
	Id                     uint64      `json:"id"                     ` // id
	PartsOutsourcingId     int         `json:"partsOutsourcingId"     ` // 工序委外订单号
	Supplier               string      `json:"supplier"               ` // 供应商
	OutputMaterialCode     int         `json:"outputMaterialCode"     ` // 产出物料编码
	OutputMaterialName     string      `json:"outputMaterialName"     ` // 产出物料名称
	OutputRequiredQuantity int         `json:"outputRequiredQuantity" ` // 产出需求数量
	OutputUnit             string      `json:"outputUnit"             ` // 产出单位
	PlanedReceiveTime      *gtime.Time `json:"planedReceiveTime"      ` // 计划收货日期
	QuantityInWarehouse    int         `json:"quantityInWarehouse"    ` // 已入库数量
	QuantityNotInWarehouse int         `json:"quantityNotInWarehouse" ` // 未入库数量
	InputMaterialCode      int         `json:"inputMaterialCode"      ` // 投入物料编码
	InputMaterialName      string      `json:"inputMaterialName"      ` // 投入物料名称
	InputRequiredQuantity  int         `json:"inputRequiredQuantity"  ` // 投入需求数量
	InputRequiredUnit      string      `json:"inputRequiredUnit"      ` // 投入需求单位
	DeliveryQuantity       int         `json:"deliveryQuantity"       ` // 已发货数量
	UndeliveryQuantity     int         `json:"undeliveryQuantity"     ` // 未发货数量
	PlanedDeliveryTime     *gtime.Time `json:"planedDeliveryTime"     ` // 计划发货日期
	OutApply               int         `json:"outApply"               ` // 出库申请： 0 已发送 1 未发送
	CreatedAt              *gtime.Time `json:"createdAt"              ` // 创建时间
	UpdatedAt              *gtime.Time `json:"updatedAt"              ` // 更新时间
	DeletedAt              *gtime.Time `json:"deletedAt"              ` // 删除时间
}
