// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TProcessOutsourcingOrder is the golang structure for table t_process_outsourcing_order.
type TProcessOutsourcingOrder struct {
	Id                     uint64      `json:"id"                     ` // id
	ProcessOutsourcingId   int         `json:"processOutsourcingId"   ` // 工序委外订单号
	ProductionId           int         `json:"productionId"           ` // 关联的生成订单号
	Supplier               string      `json:"supplier"               ` // 供应商
	OutputMaterialCode     int         `json:"outputMaterialCode"     ` // 产出物料编码
	OutputMaterialName     string      `json:"outputMaterialName"     ` // 产出物料名称
	OutputRequiredQuantity int         `json:"outputRequiredQuantity" ` // 产出需求数量
	OutputUnit             string      `json:"outputUnit"             ` // 产出单位
	PlanedReceiveTime      *gtime.Time `json:"planedReceiveTime"      ` // 计划收货日期
	QuantityReceived       int         `json:"quantityReceived"       ` // 已收货数量
	QuantityUnreceived     int         `json:"quantityUnreceived"     ` // 未收货数量
	InputMaterialCode      int         `json:"inputMaterialCode"      ` // 投入物料编码
	InputMaterialName      string      `json:"inputMaterialName"      ` // 投入物料名称
	InputRequiredQuantity  int         `json:"inputRequiredQuantity"  ` // 投入需求数量
	InputRequiredUnit      string      `json:"inputRequiredUnit"      ` // 投入需求单位
	DeliveryQuantity       int         `json:"deliveryQuantity"       ` // 已发货数量
	UndeliveryQuantity     int         `json:"undeliveryQuantity"     ` // 未发货数量
	PlanedDeliveryTime     *gtime.Time `json:"planedDeliveryTime"     ` // 计划发货日期
	Note                   string      `json:"note"                   ` // 备注
	OperationStatus        int         `json:"operationStatus"        ` // 操作： 0 现场发货 1 现场收货
	CreatedAt              *gtime.Time `json:"createdAt"              ` // 创建时间
	UpdatedAt              *gtime.Time `json:"updatedAt"              ` // 更新时间
	DeletedAt              *gtime.Time `json:"deletedAt"              ` // 删除时间
}
