// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TProcurementOrder is the golang structure for table t_procurement_order.
type TProcurementOrder struct {
	Id                     uint64      `json:"id"                     ` // id
	ProcurementId          int         `json:"procurementId"          ` // 采购订单号
	OrderDetailLineNum     int         `json:"orderDetailLineNum"     ` // 订单详情行号
	Supplier               string      `json:"supplier"               ` // 供应商
	MaterialId             int         `json:"materialId"             ` // 物料编码
	MaterialName           string      `json:"materialName"           ` // 物料名称
	QuantityRequired       int         `json:"quantityRequired"       ` // 需求数量
	QuantityInWarehouse    int         `json:"quantityInWarehouse"    ` // 已入库数量
	QuantityNotInWarehouse int         `json:"quantityNotInWarehouse" ` // 未入库数量
	PurchasingUnit         string      `json:"purchasingUnit"         ` // 采购单位
	SettlementUnit         string      `json:"settlementUnit"         ` // 结算单位
	PlanArrivalDate        *gtime.Time `json:"planArrivalDate"        ` // 计划到货日期
	Status                 int         `json:"status"                 ` // 入库操作 0 未入库 1入库
	CreatedAt              *gtime.Time `json:"createdAt"              ` // 创建时间
	UpdatedAt              *gtime.Time `json:"updatedAt"              ` // 更新时间
	DeletedAt              *gtime.Time `json:"deletedAt"              ` // 删除时间
}
