// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TProductionOrder is the golang structure for table t_production_order.
type TProductionOrder struct {
	Id                     uint64      `json:"id"                     ` // id
	ProductionId           int         `json:"productionId"           ` // 生产订单号
	OutputMaterialCode     int         `json:"outputMaterialCode"     ` // 产出物料编码
	OutputMaterialName     string      `json:"outputMaterialName"     ` // 产出物料名称
	OutputRequiredQuantity int         `json:"outputRequiredQuantity" ` // 产出需求数量
	OutputUnit             string      `json:"outputUnit"             ` // 产出单位
	QuantityInWarehouse    int         `json:"quantityInWarehouse"    ` // 已入库数量
	QuantityNotInWarehouse int         `json:"quantityNotInWarehouse" ` // 未入库数量
	StartWorkTime          *gtime.Time `json:"startWorkTime"          ` // 开工时间
	PlanedCompletionTime   *gtime.Time `json:"planedCompletionTime"   ` // 计划完工时间
	InputMaterialCode      int         `json:"inputMaterialCode"      ` // 投入物料编码
	InputRequiredUnit      string      `json:"inputRequiredUnit"      ` // 投入需求单位
	InputRequiredQuantity  int         `json:"inputRequiredQuantity"  ` // 投入需求数量
	ReceivedQuantity       int         `json:"receivedQuantity"       ` // 已领数量
	UnreceivedQuantity     int         `json:"unreceivedQuantity"     ` // 未领数量
	InApply                int         `json:"inApply"                ` // 出库申请 0 未发送 1 已发送
	OutApply               int         `json:"outApply"               ` // 入库申请 0 未发送 1 已发送
	CreatedAt              *gtime.Time `json:"createdAt"              ` // 创建时间
	UpdatedAt              *gtime.Time `json:"updatedAt"              ` // 更新时间
	DeletedAt              *gtime.Time `json:"deletedAt"              ` // 删除时间
}
